# Generated by Django 6.0.5 on 2026-05-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon raqam')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Xabar')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Tekshirildimi?')),
                ('status', models.CharField(choices=[('new', 'Yangi so‘rov'), ('called', 'Qo‘ng‘iroq qilindi'), ('not_answered', 'Javob bermadi'), ('booked', 'Qabulga yozildi'), ('came', 'Keldi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=30, verbose_name='Holati')),
                ('operator_note', models.TextField(blank=True, null=True, verbose_name='Operator izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqt')),
            ],
            options={
                'verbose_name': 'Bog‘lanish so‘rovi',
                'verbose_name_plural': 'Bog‘lanish so‘rovlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
