# Generated by Django 6.0.5 on 2026-05-07 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.SH.')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('wisdom_visible', models.BooleanField(default=True)),
                ('show_base', models.BooleanField(default=True)),
                ('occlusal_visible', models.BooleanField(default=True)),
                ('show_healthy_pulp', models.BooleanField(default=True)),
                ('edentulous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['full_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OdontogramToothState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_no', models.PositiveSmallIntegerField(verbose_name='Tish raqami')),
                ('tooth_selection', models.CharField(choices=[('none', "Tish yo'q"), ('tooth-base', 'Doimiy tish'), ('milktooth', 'Sut tish'), ('implant', 'Implant'), ('tooth-crownprep', 'Koronaga tayyorlangan tish'), ('tooth-under-gum', 'Milk ostidagi tish'), ('no-tooth-after-extraction', 'Olib tashlangan tish')], default='tooth-base', max_length=40, verbose_name='Baza')),
                ('filling_material', models.CharField(choices=[('none', "To'ldirish yo'q"), ('amalgam', 'Amalgam'), ('composite', 'Kompozit'), ('gic', 'GIC'), ('temporary', 'Vaqtinchalik')], default='none', max_length=30, verbose_name='Plomba turi')),
                ('endo', models.CharField(choices=[('none', "Sog'lom ildiz"), ('endo-medical-filling', 'Dori bilan ildiz davolash'), ('endo-filling', "Ildiz to'ldirilgan"), ('endo-filling-incomplete', "To'liq bo'lmagan ildiz to'ldirish"), ('endo-glass-pin', 'Shisha pin'), ('endo-metal-pin', 'Metall pin')], default='none', max_length=40, verbose_name='Ildiz holati')),
                ('mobility', models.CharField(choices=[('none', 'Hech biri'), ('m1', '1-daraja'), ('m2', '2-daraja'), ('m3', '3-daraja')], default='none', max_length=10, verbose_name='Harakatchanlik')),
                ('caries_mesial', models.BooleanField(default=False)),
                ('caries_distal', models.BooleanField(default=False)),
                ('caries_buccal', models.BooleanField(default=False)),
                ('caries_lingual', models.BooleanField(default=False)),
                ('caries_occlusal', models.BooleanField(default=False)),
                ('caries_subcrown', models.BooleanField(default=False)),
                ('fissure_sealing', models.BooleanField(default=False)),
                ('pulp_inflam', models.BooleanField(default=False)),
                ('endo_resection', models.BooleanField(default=False)),
                ('parapulpal_pin', models.BooleanField(default=False)),
                ('periodontal_inflammation', models.BooleanField(default=False)),
                ('periapical_inflammation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_states', to='doctor.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Tish holati',
                'verbose_name_plural': 'Tish holatlari',
                'ordering': ['tooth_no'],
                'unique_together': {('customer', 'tooth_no')},
            },
        ),
    ]
