# Generated by Django 6.0.5 on 2026-05-11 13:09

import django.utils.timezone
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_history_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='customer',
            name='allergy_details',
            field=models.TextField(blank=True, verbose_name='Allergiya tafsiloti'),
        ),
        migrations.AddField(
            model_name='customer',
            name='arrived_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qachon kelgan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='customer',
            name='chronic_disease_details',
            field=models.TextField(blank=True, verbose_name='Surunkali kasallik tafsiloti'),
        ),
        migrations.AddField(
            model_name='customer',
            name='complaint',
            field=models.TextField(blank=True, verbose_name='Shikoyati'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_allergy',
            field=models.BooleanField(default=False, verbose_name='Allergiyasi bormi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_chronic_disease',
            field=models.BooleanField(default=False, verbose_name='Surunkali kasalligi bormi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.FileField(blank=True, upload_to=doctor.models.customer_photo_upload_to, verbose_name='Rasmi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('website', 'Website'), ('telegram', 'Telegram'), ('friend', 'Tanishi orqali'), ('doctor', 'Shifokor tavsiyasi'), ('returning', 'Oldingi mijoz'), ('other', 'Boshqa')], default='instagram', max_length=20, verbose_name='Kim tavsiya qilgan'),
        ),
    ]
