# Generated by Django 6.0.5 on 2026-05-11 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_customer_latitude_customer_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Klinika nomi')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klinika',
                'verbose_name_plural': 'Klinikalar',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Sarlavha')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('starts_at', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('ends_at', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('status', models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('done', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='planned', max_length=20)),
                ('color', models.CharField(blank=True, default='#0e7490', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctor.customer')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.clinic')),
            ],
            options={
                'verbose_name': 'Qabul jadvali',
                'verbose_name_plural': 'Qabul jadvallari',
                'ordering': ['starts_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='doctor.clinic', verbose_name='Klinika'),
        ),
        migrations.CreateModel(
            name='ClinicMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Stomatolog'), ('staff', 'Xodim')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='doctor.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Klinika a'zosi",
                'verbose_name_plural': "Klinika a'zolari",
                'ordering': ['clinic__name', 'user__username'],
                'unique_together': {('clinic', 'user')},
            },
        ),
    ]
