# Generated by Django 6.0.5 on 2026-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_clinic_appointment_customer_clinic_clinicmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmembership',
            name='can_add_customers',
            field=models.BooleanField(default=True, verbose_name="Mijoz qo'shish"),
        ),
        migrations.AddField(
            model_name='clinicmembership',
            name='can_edit_medical_records',
            field=models.BooleanField(default=False, verbose_name='Tibbiy kartani tahrirlash'),
        ),
        migrations.AddField(
            model_name='clinicmembership',
            name='can_manage_staff',
            field=models.BooleanField(default=False, verbose_name='Xodimlarni boshqarish'),
        ),
        migrations.AddField(
            model_name='clinicmembership',
            name='can_view_calendar',
            field=models.BooleanField(default=True, verbose_name='Qabul jadvali'),
        ),
        migrations.AddField(
            model_name='clinicmembership',
            name='can_view_customers',
            field=models.BooleanField(default=True, verbose_name="Mijozlar ro'yxati"),
        ),
        migrations.AddField(
            model_name='clinicmembership',
            name='can_view_dashboard',
            field=models.BooleanField(default=True, verbose_name='Dashboard'),
        ),
    ]
