# Generated by Django 6.0.5 on 2026-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_clinicmembership_can_add_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmembership',
            name='can_access_clinic',
            field=models.BooleanField(default=True, verbose_name='Klinikaga kirish'),
        ),
    ]
